# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in transitive dependency resolution mode.
# This is the default starting from Gradle 3.0.
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# Android Gradle plugin
android.enableJetifier=true
android.useAndroidX=true

# Build
android.enableMultidex=true
android.minSdkVersion=24
android.compileSdkVersion=34
